version: '3.7'

services:
  web:
    image: docker.pkg.github.com/geovanaramos/calango-online-judge/coj:latest
    command: gunicorn coj.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
      - judge

  judge:
    image: docker.pkg.github.com/geovanaramos/calango-judge-service/service:latest
    expose:
      - 8080

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
