version: '3.7'

services:
  web:
    build:
      context: web
      dockerfile: Dockerfile.prod
    command: gunicorn coj.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
