# Generated by Django 3.1.4 on 2021-01-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APC', 'Algoritmos e Programação para Computadores')], max_length=50, verbose_name='Nome')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semestre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='accounts.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Enunciado')),
                ('subject', models.CharField(choices=[('SEQ', 'Estruturas Sequenciais e Condicionais'), ('MOD', 'Modularização'), ('COND', 'Estruturas Condionais e de Repetição'), ('VET', 'Vetores')], max_length=40, verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(help_text='Cada entrada separada por vírgula e em ordem de leitura.', verbose_name='Entradas')),
                ('output', models.TextField(help_text='String única com \\n explícito se necessário.', verbose_name='Saída')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='judge.question', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Caso de Teste',
                'verbose_name_plural': 'Casos de Teste',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Código')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submetido em')),
                ('judged_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Julgado em')),
                ('result', models.CharField(blank=True, choices=[('ACCEPTED', 'Aceito'), ('WRONG_ANSWER', 'Resposta Incorreta'), ('PRESENTATION_ERROR', 'Erro de Apresentação'), ('COMPILATION_ERROR', 'Erro de Compilação'), ('RUNTIME_ERROR', 'Erro de Execução'), ('TIME_LIMIT_EXCEEDED', 'Limite de Tempo Excedido'), ('WAITING', 'Aguardando')], editable=False, max_length=30, null=True, verbose_name='Resultado')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='judge.question', verbose_name='Questão')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='accounts.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
            },
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('questions', models.ManyToManyField(related_name='lists', to='judge.Question', verbose_name='Questões')),
            ],
            options={
                'verbose_name': 'Lista de Exercícios',
                'verbose_name_plural': 'Listas de Exercicíos',
            },
        ),
        migrations.CreateModel(
            name='ListSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('due_date', models.DateTimeField(verbose_name='Data de Término')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='judge.courseclass', verbose_name='Turma')),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='judge.questionlist', verbose_name='Lista de Exercícios')),
            ],
            options={
                'verbose_name': 'Agendamento de Lista',
                'verbose_name_plural': 'Agendamentos de Listas',
            },
        ),
    ]
