# Generated by Django 3.1.4 on 2021-01-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210101_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa?'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('SEQ', 'Estruturas Sequenciais e Condicionais'), ('MOD', 'Modularização'), ('COND', 'Estruturas Condionais e de Repetição'), ('VET', 'Vetores')], max_length=60, verbose_name='Assunto'),
        ),
    ]
