# Generated by Django 3.1.4 on 2021-02-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ocultar?'),
        ),
    ]
