# Generated by Django 3.1.4 on 2021-07-07 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_testcase_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_evaluative',
            field=models.BooleanField(default=True, verbose_name='Avaliativa?'),
        ),
        migrations.AddField(
            model_name='submission',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='judge.courseclass', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='list_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='judge.listschedule', verbose_name='Agendamento'),
        ),
    ]
