# Generated by Django 3.1.4 on 2021-07-25 00:15

from django.db import migrations


def migrate_m2m_to_through_m2m(apps, schema_editor):
    CourseClass = apps.get_model('judge', 'CourseClass')

    for course_class in CourseClass.objects.all():
        for student in course_class.students.all():
            if student.user.last_login and student.first_login:
                first_login = student.first_login
                last_login = student.user.last_login
            elif student.user.last_login and not course_class.is_active:
                first_login = student.first_login
                last_login = student.user.last_login
            else:
                first_login = None
                last_login = None

            course_class.students2.add(student, through_defaults={'first_login': first_login, 'last_login': last_login})


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20210724_2113'),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_through_m2m),
    ]
