# Generated by Django 3.1.4 on 2021-07-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20210724_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='students',
        ),
    ]
