# Generated by Django 3.1.4 on 2021-07-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_first_login'),
        ('judge', '0007_auto_20210724_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', through='judge.Enrollment', to='accounts.Student', verbose_name='Alunos'),
        ),
    ]
