# Generated by Django 3.1.4 on 2021-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20210724_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='is_synthesis_required',
            field=models.BooleanField(default=False, verbose_name='Síntese do algoritmo obrigatória?'),
        ),
    ]
