# Generated by Django 3.1.4 on 2021-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primeiro Login'),
        ),
    ]
